version: '3.4'

services:
  db:
    image: postgres
    networks:
      - do-more-with-less-net
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web_api:
    hostname: web-api
    build:
      context: web_api
    command: "./entrypoint.sh"  
    networks:
      - do-more-with-less-net
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./web_api:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  do-more-with-less-net:
    driver: bridge
