service: do-more-with-less

configValidationMode: off
plugins:
  - serverless-dynamodb-autoscaling
  - serverless-prune-plugin
  - serverless-python-requirements
  - serverless-plugin-select
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-offline-ssm
  - serverless-offline

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 10
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  serverless-offline:
    host: 0.0.0.0
  pythonRequirements:
    useDownloadCache: ${strToBool(${env:USE_CACHE, 'true'})}
    useStaticCache: ${strToBool(${env:USE_CACHE, 'true'})}
    dockerizePip: non-linux
    slim: true
    zip: true
  serverless-offline-ssm:
    stages:
      - local
    ssm:
      '/bm-local/backend/SECURITY_GROUP_IDS': 'sample-value-goes-here'
      '/bm-local/backend/SUBNET_IDS': 'sample-value'
      '/bm-local/backend/DB_PASS': 'plumbs'
      '/bm-local/backend/DB_USER': 'plumbs'
      '/bm-local/backend/DB_NAME': 'plumbs'
      '/bm-local/backend/DB_HOST': 'db'
      '/bm-local/backend/DB_PORT': '3306'
      '/bm-local/backend/SECRET_KEY': '-pt5ibcuy$&pbf8@=z1ke3nt3t+2m(mqdy@#5qad&o!7q1u6kt'
      '/misc/common/AWS_ACCESS_KEY_ID': 'not supported'
      '/misc/common/AWS_SECRET_ACCESS_KEY': 'not supported'

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 900 # max lambda timeout 15 minute
  websocketApiName: do-more-with-less
  websocketApiRouteSelectionExpression: $request.body.action

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - venv/**
    - .gitignore
    - .DS_Store
    - npm-debug.log
    - .serverless/**
    - .serverless_plugins/**


	
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
