service: do-more-with-less

configValidationMode: off
plugins:
  - serverless-dynamodb-autoscaling
  - serverless-prune-plugin
  - serverless-python-requirements
  - serverless-plugin-select
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-offline-ssm
  - serverless-offline

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 10
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  serverless-offline:
    host: 0.0.0.0
  pythonRequirements:
    useDownloadCache: ${strToBool(${env:USE_CACHE, 'true'})}
    useStaticCache: ${strToBool(${env:USE_CACHE, 'true'})}
    dockerizePip: non-linux
    slim: true
    zip: true
  serverless-offline-ssm:
    stages:
      - local
    ssm:
      ${file(resources/custom/offline-ssm.yml)}

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds: ${ssm:/bm-${self:provider.stage}/backend/SECURITY_GROUP_IDS, null}
    subnetIds: ${ssm:/bm-${self:provider.stage}/backend/SUBNET_IDS, null}
  environment:
    DB_PASS: ${ssm:/bm-${self:provider.stage}/backend/DB_PASS, null}
    DB_USER: ${ssm:/bm-${self:provider.stage}/backend/DB_USER, null}
    DB_NAME: ${ssm:/bm-${self:provider.stage}/backend/DB_NAME, null}
    DB_HOST: ${ssm:/bm-${self:provider.stage}/backend/DB_HOST, null}
    DB_PORT: ${ssm:/bm-${self:provider.stage}/backend/DB_PORT, null}
    ENVIRONMENT: ${ssm:/bm-${self:provider.stage}/backend/ENVIRONMENT, null}
    STAGE: ${opt:stage, 'dev'}
    SECRET_KEY: ${ssm:/bm-${self:provider.stage}/backend/SECRET_KEY, null}
    AWS_SES_ACCESS_KEY_ID: ${ssm:/misc/common/AWS_ACCESS_KEY_ID, null}
    AWS_SES_SECRET_ACCESS_KEY: ${ssm:/misc/common/AWS_SECRET_ACCESS_KEY, null}
    AWS_SES_REGION_NAME: ${ssm:/misc/common/AWS_SES_REGION_NAME, null}
  timeout: 900 # max lambda timeout 15 minute
  websocketApiName: do-more-with-less
  websocketApiRouteSelectionExpression: $request.body.action

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - venv/**
    - .gitignore
    - .DS_Store
    - npm-debug.log
    - .serverless/**
    - .serverless_plugins/**
